spring:
  data:
    redis:
      host: foodlog-redis
      port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: com.example.foodlog.global.config.CustomMySQLDialect
        default_batch_fetch_size: 500
        show_sql: true
        format_sql: true
        use_sql_comments: true
    # script 파일이 hibernate 초기화 이후 동작하게 하기 위한 옵션
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/data.sql








