server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_foodlog?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: com.example.foodlog.global.config.CustomMySQLDialect
        format_sql: true
        default_batch_fetch_size: 1000
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/test-data.sql