spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodlog
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 500
        show_sql: true
        format_sql: true
        use_sql_comments: true
    # script 파일이 hibernate 초기화 이후 동작하게 하기 위한 옵션
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/data.sql

fcm:
  key:
    path: firebase/tastylog-353f1-firebase-adminsdk-444sl-674cd6dd67.json
    scope: https://fcm.googleapis.com/v1/projects/tastylog-353f1/messages:sends



